export const Users = [
    {
        id:1,
        profilePicture: "person/1.jpeg",
        username: "Hoang Hai",
    },
    {
        id:2,
        profilePicture: "person/2.jpeg",
        username: "Mai Anh",
    },
    {
        id:3,
        profilePicture: "person/3.jpeg",
        username: "Kim Bich",
    },
    {
        id:4,
        profilePicture: "person/4.jpeg",
        username: "Quang Hai",
    },
    {
        id:5,
        profilePicture: "person/5.jpeg",
        username: "Messi",
    },
    {
        id:6,
        profilePicture: "person/6.jpeg",
        username: "Empampel",
    },
    {
        id:7,
        profilePicture: "person/7.jpeg",
        username: "Jonh",
    },
    {
        id:8,
        profilePicture: "person/8.jpeg",
        username: "Marry",
    },
    {
        id:9,
        profilePicture: "person/9.jpeg",
        username: "Huy Losed",
    },
    {
        id:10,
        profilePicture: "person/10.jpeg",
        username: "Mai Thuy",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "I am Huy Dinh",
        photo: "post/1.jpeg",
        date:"5 mins ago",
        userId: 1,
        like: 983,
        comment: 100,
    },
    {
        id: 2,
        desc: "What do you do?",
        photo: "post/2.jpeg",
        date:"15 mins ago",
        userId: 2,
        like: 3112,
        comment: 0,
    },
    {
        id: 3,
        desc: "The end!",
        photo: "post/3.jpeg",
        date:"25 mins ago",
        userId: 3,
        like: 1132,
        comment: 880,
    },
    {
        id: 4,
        desc: "Let's go!",
        photo: "post/4.jpeg",
        date:"35 mins ago",
        userId: 4,
        like: 3352,
        comment: 760,
    },
    {
        id: 5,
        desc: "BTC to the moon",
        photo: "post/5.jpeg",
        date:"45 mins ago",
        userId: 5,
        like: 332,
        comment: 30,
    },
    {
        id: 6,
        desc: "i have 1000$",
        photo: "post/6.jpeg",
        date:"1 hours ago",
        userId: 6,
        like: 34232,
        comment: 550,
    },
    {
        id: 7,
        desc: "i want buy telephone",
        photo: "post/7.jpeg",
        date:"2 hours ago",
        userId: 7,
        like: 312,
        comment: 100,
    },
    {
        id: 8,
        desc: "How it's going?",
        photo: "post/8.jpeg",
        date:"5 hours ago",
        userId: 8,
        like: 112,
        comment: 80,
    },
    {
        id: 9,
        desc: "Go home",
        photo: "post/9.jpeg",
        date:"3 hours ago",
        userId: 9,
        like: 325,
        comment: 40,
    },
    {
        id: 10,
        desc: "i go to pagoda!",
        photo: "post/10.jpeg",
        date:"9 hours ago",
        userId: 10,
        like: 320,
        comment: 100,
    }
]